### ISSUE TITLE
Docker image for testing

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#146]
Create docker image that can run all the tests that travis runs so tests can be easily be run on any computer without setup.

**Comment by k1sul1** [comment]
You should be able to run the tests easily using [Seravo/wordpress](https://github.com/Seravo/wordpress). It's what I use for the development of the plugin. 

https://github.com/Seravo/woo-pakettikauppa#running-tests-locally

In practice it hasn't been that easy. Before I started tweaking things today, I got `PHP Fatal error:  Class PHPUnit_Util_Test may not inherit from final class (PHPUnit\Util\Test) in /tmp/wordpress-tests-lib/includes/phpunit6-compat.php on line 18`. That isn't supposed to be a problem according to several people, including WP core devs.

By downgrading all the way to 5.7.27 AND by disabling this in tests/bootstrap, the tests pass. 

```
set_error_handler(
  function( $errno, $errstr, $errfile, $errline ) {
    throw new RuntimeException($errstr . ' on line ' . $errline . ' in file ' . $errfile);
  }
);
```
They will not pass without disabling this, as there are notices coming from WP core. Alternatively this handler could be reworked to only complain about issues in the plugin folder.

**Comment by joosev** [comment]
Ok. That seravo plugin helps but makes still testing little bit difficult. I will take that seravo development thingie and try to create a new docker container from that, that would work better.

**Comment by k1sul1** [comment]
`fix/local-tests` branch should now work just as https://github.com/Seravo/woo-pakettikauppa#running-tests-locally says it does. 

You could run bin/install-local-tests.sh without a VM or a docker container, assuming you have a mysql server running. I find the docker container easier.

**Comment by joosev** [comment]
I did something like this:

Dockerfile:
```
FROM alpine

RUN apk update && apk upgrade && apk add php7 wget curl php7-curl bash subversion mysql-client php7-tokenizer php7-simplexml php7-phar php7-dom php7-mysqli

COPY . /wc-pakettikauppa/
WORKDIR /wc-pakettikauppa/bin
```

docker-compose.yml
```
version: '3'

services:
  plugin-test:
    image: pakettikauppa/woo-plugin-tester
    build: .
    environment:
      SNIFF: 1
      DB_HOST: db
      DB_PASS: root
      DB_USER: root
      DB_NAME: wordpress

#    volumes:
#    - .:/plugin/
  db:
   image: mysql:5.7

   environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
```

I modified install-local-tests.sh:

Added these line:
´´´
DB_NAME=${DB_NAME-wordpress_test}
DB_USER=${DB_USER-root}
DB_PASS=${DB_PASS-}
DB_HOST=${DB_HOST-localhost}
´´´

ANd modified this line:
    bash bin/install-wp-tests.sh ${DB_NAME} ${DB_USER} ${DB_PASS} ${DB_HOST} $WP_VERSION

And then new file: bin/install-and-run.sh 
#!/bin/bash
./install-local-tests.sh
./run-local-tests.sh

And then running is just like:
```
docker-compose up -d
docker-compose run plugin-test bash run-and-install.sh
```

last line could be easifly fixed by putting it in the dockerfile as entrypoint


Did not commit these because it might break alot of stuff.
